# 🧩 LeetCode 389: Find the Difference

**Platform:** LeetCode
**Difficulty:** Easy
**Language:** Java ☕

---

## 📌 Problem Description

You are given two strings `s` and `t`.

String `t` is generated by randomly shuffling string `s` and then adding one more letter at a random position.

Return the letter that was added to `t`.

---

## 🧠 Approach

* Use XOR operation to cancel out matching characters
* Remaining character will be the extra one

---

## 🔑 Key Points

* XOR of same characters = 0
* XOR of all characters leaves the extra character
* Efficient and clean approach

---

## ⏱️ Complexity

* Time: O(n)
* Space: O(1)

---

## 💻 Code

class Solution {
    public char findTheDifference(String s, String t) {
        char result = 0;
        for(char c : s.toCharArray()){
            result ^= c;
        }
        for(char c : t.toCharArray()){
            result ^= c;
        }
        return result;
    }
}

---

## 💡 Interview Insight

* Classic XOR trick problem
* Tests bit manipulation understanding
* Optimized solution without extra space

---

## ✅ Status

✔ Solved successfully
✔ Optimal O(n) solution
✔ Interview-ready implementation

---

*This solution is part of my Data Structures & Algorithms (DSA) practice in Java.*
